openapi: 3.1.0
info:
  title: EXO 1
  description: OpenAPI specification for the EXO 1 API.
  version: 1.0.0
paths:
  /ping:
    get:
      summary: returns a pong
      responses:
        '200':
          description: returned a pong
          content:
            text/plain:
              schema:
                type: string

  
