openapi: 3.0.0
info:
  title: User managing API
  version: 1.0.0
paths:
  /users:
    get:
      summary: User list
      description: Récupère une liste d'utilisateurs avec pagination.
      parameters:
        - name: page
          in: query
          description: Page number
          schema:
            type: number
            default: 1
        - name: size
          in: query
          description: Page size
          schema:
            type: number
            default: 20
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    email:
                      type: string
              examples:
                user_list_exemple:
                  value:
                    - id: 1
                      name: Alice
                      email: alice@example.com
                    - id: 2
                      name: Bob
                      email: bob@example.com
        '400':
          description: Mauvais types de paramètres fournis.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"

