openapi: 3.0.0
info:
  title: User managing API
  version: 1.0.0
paths:
  /users:
    get:
      summary: User list
      description: Récupère une liste d'utilisateurs avec pagination.
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Size'
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                user_list_exemple:
                  value:
                    - id: 1
                      name: Alice
                      email: alice@example.com
                    - id: 2
                      name: Bob
                      email: bob@example.com
        '400':
          description: Mauvais types de paramètres fournis.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
          example: "Bad types for provided query parameters"
  parameters:
    Page:
      name: page
      in: query
      description: Page number
      schema:
        type: number
        default: 1
    Size:
      name: size
      in: query
      description: Page size
      schema:
        type: number
        default: 20