openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                    title:
                      type: string
                      example: "Do the shopping"
                    completed:
                      type: boolean
                      example: false
    post:
      summary: Create one or more tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  title:
                    type: string
                    example: "Do the shopping"
                  completed:
                    type: boolean
                    example: false
      responses:
        '201':
          description: Tasks successfully created.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                    title:
                      type: string
                      example: "Do the shopping"
                    completed:
                      type: boolean
                      example: false