openapi: 3.0.0
info:
  title: API with Authentication and Tags
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /orders:
    get:
      summary: Get paginated list of orders
      tags:
        - Orders
      responses:
        '200':
          description: A list of orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Create a new order
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Apple"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-10-26T10:00:00Z"
        price:
          type: number
          format: float
          example: 0.99
    Order:
      type: object
      properties:
        identifier:
          type: integer
          example: 101
        customer_name:
          type: string
          example: "Alice"
        creation_datetime:
          type: string
          format: date-time
          example: "2025-08-28T14:00:00Z"
        total_amount:
          type: number
          format: float
          example: 50.75